### ISSUE TITLE
Sun-300 reader supported?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [armando-basile/monosim#24]
```
What steps will reproduce the problem?
1. Configure monosim 2.0.0.r108 to be on the appropriate serial port
2. Connect to the SIM
3.

What is the expected output? What do you see instead?
I hoped it might connect, but I get an error box with A0A4000002 

What version of the product are you using? On what operating system?
GTK version on Windows Vista

Please provide any additional information below.
The reader seems to work with the (somewhat clunky!) supplied application 
(MagicSIM) but I had hoped it would work with your s/w...

If it isn't a compatible device, maybe a note excluding it would save others 
time...

Rgds
Neil
```

Original issue reported on code.google.com by `bl06...@gmail.com` on 15 Oct 2013 at 1:09

**Comment by armando-basile** [comment]
i think that isn't standard pcsc reader. The only one reader (not pcsc) supported from monosim is serial reader SmartMouse Phoenix.

* for list of standard pcsc readers on **ms windows** can find official list on [this page](http://www.pcscworkgroup.com/compatibleproducts/cardreaders.php) on PC/SC Workgroup website

* for list of standard pcsc readers on **linux** can find official list on [this page](https://pcsclite.alioth.debian.org/ccid/supported.html) on Pcsclite project website
