### ISSUE TITLE
Error when in connect SIM card ERROR - A02A0040

### ISSUE THREAD

**Issue by GoogleCodeExporter** [armando-basile/monosim#27]
```
What steps will reproduce the problem?
1.selecting Reader --> /dev/ttyUSB0
2.connect to sim card
3.

What is the expected output? What do you see instead?
ERROR - A02A0040

What version of the product are you using? On what operating system?
OS - Ubuntu 12.04 
Product - 
http://www.ebay.in/itm/like/usb-mobile-phone-sim-card-data-backup-copy-reader-co
py-writer-gsm-cdma-/310838770115?pt=in_mobile_accessories

Please provide any additional information below.

```

Original issue reported on code.google.com by `meerr...@gmail.com` on 25 Jun 2014 at 6:48

**Comment by LightningStalker** [comment]
I am getting a similar A0A4000002, is this the same error?
It's one of these:
https://www.amazon.com/Insten-Cell-Phone-Reader-Backup/dp/B004I1IET6

**Comment by armando-basile** [comment]
It haven't pcsc driver and isn't a SmartMouse card reader, so isn't supported.
You can see supported readers here: https://pcsclite.alioth.debian.org/select_readers/
